version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: rhythmlink_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - app-network
    ports:
      - "3306:3306"

  rhythmlink-backend:
    build: .
    container_name: rhythmlink-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: rhythmlink_db
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    command: >
      sh -c "
      until nc -z -v -w30 mysql 3306; do
        echo 'Waiting for MySQL to be ready...';
        sleep 1;
      done;
      npm run dev"

  recommendation-service:
    build:
      context: ./ml_model # Assuming the Python app is in the `ml_model` folder
    container_name: recommendation-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: rhythmlink_db
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./ml_model:/app # Mount the Python application files

networks:
  app-network:
    driver: bridge
